### ISSUE TITLE
指摘箇所メモ

### ISSUE THREAD

**Issue by HiroshiKubo** [HiroshiKubo/RSSImagesCrawler#1]
- [x] {}から[]に変更でも良いのでは
- [x] rss_dataでなく、target_urlsで良いのでは

**Comment by june29** [comment]
これ Close してもよさそう :ok_hand:

**Comment by june29** [comment]
ひろしくん、もしこのメッセージに気付いていたら `june29.jp ｱｯﾄ gmail.com` まで連絡ください :pray:
